import argparse
import datetime
import os
import shutil
import sys
from typing import Any

from aethel import session
from aethel.config import load_config
from aethel.linter import (
    check_report_file,
    run_linter,  # noqa: F401  (kept for backward-compatible imports)
)
from aethel.markers import (  # noqa: F401  (re-exported for backward-compatible imports)
    extract_managed_block,
    parse_block_id,
    replace_managed_block,
)

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")

LINTER_WRAPPER = """#!/usr/bin/env python3
# Autogenerated Aethel wrapper script
import sys
try:
    from aethel.linter import main
except ImportError:
    print("Error: 'aethel' package not found in Python path. Please run 'pip install aethel' or install it globally.")
    sys.exit(1)

if __name__ == "__main__":
    main()
"""

PRE_COMMIT_HOOK = """#!/bin/sh
# Autogenerated Aethel Git pre-commit hook
echo "=== Running Aethel pre-commit verification ==="
if [ -f "./venv/Scripts/python" ]; then
  ./venv/Scripts/python prompt_linter.py
elif [ -f "./venv/bin/python" ]; then
  ./venv/bin/python prompt_linter.py
else
  python prompt_linter.py
fi
"""


# Helper to copy template files
def copy_template(src_name: str, dest_name: str, dest_dir: str, overwrite: bool = False) -> bool:
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    dest_path = os.path.join(dest_dir, dest_name)

    if not os.path.exists(src_path):
        print(f"Error: Template source '{src_path}' not found.")
        return False

    if os.path.exists(dest_path) and not overwrite:
        print(f"Skipping existing file: {dest_name}")
        return False

    abs_workspace_root = os.path.abspath(dest_dir).replace('\\', '/')
    try:
        with open(src_path, "r", encoding="utf-8") as f:
            content = f.read()

        content = content.replace("{WORKSPACE_ROOT}", abs_workspace_root)

        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(content)

        try:
            shutil.copymode(src_path, dest_path)
        except Exception:
            pass

        print(f"Created/Updated: {dest_name}")
        return True
    except Exception as e:
        print(f"Error copying template {src_name}: {e}")
        return False


def render_template(src_name: str, dest_dir: str) -> str | None:
    """Read a template and substitute {WORKSPACE_ROOT}, returning the text."""
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    if not os.path.exists(src_path):
        print(f"Error: Template source '{src_path}' not found.")
        return None
    abs_workspace_root = os.path.abspath(dest_dir).replace('\\', '/')
    with open(src_path, "r", encoding="utf-8") as f:
        return f.read().replace("{WORKSPACE_ROOT}", abs_workspace_root)


# Helper to recursively copy directories (destructive replace)
def copy_template_dir(src_name: str, dest_name: str, dest_dir: str, overwrite: bool = False) -> bool:
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    dest_path = os.path.join(dest_dir, dest_name)

    if not os.path.exists(src_path):
        print(f"Error: Template folder source '{src_path}' not found.")
        return False

    if os.path.exists(dest_path):
        if overwrite:
            shutil.rmtree(dest_path)
        else:
            print(f"Skipping existing folder: {dest_name}")
            return False

    shutil.copytree(src_path, dest_path)
    print(f"Created/Updated folder: {dest_name}")
    return True


def merge_template_dir(src_name: str, dest_name: str, dest_dir: str) -> None:
    """Copy template files over an existing directory without deleting user files.

    Unlike copy_template_dir(overwrite=True), this never removes files the user
    added under the destination tree — it only refreshes the files Aethel ships.
    """
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    dest_path = os.path.join(dest_dir, dest_name)
    if not os.path.exists(src_path):
        print(f"Error: Template folder source '{src_path}' not found.")
        return

    for root, _dirs, files in os.walk(src_path):
        rel = os.path.relpath(root, src_path)
        target_root = dest_path if rel == "." else os.path.join(dest_path, rel)
        os.makedirs(target_root, exist_ok=True)
        for fname in files:
            shutil.copy2(os.path.join(root, fname), os.path.join(target_root, fname))
    print(f"Merged template folder (non-destructive): {dest_name}")


def write_linter_wrapper(dest_dir: str) -> None:
    with open(os.path.join(dest_dir, "prompt_linter.py"), "w", encoding="utf-8") as f:
        f.write(LINTER_WRAPPER)


def write_pre_commit_hook(dest_dir: str, verb: str) -> None:
    git_dir = os.path.join(dest_dir, ".git")
    if not os.path.isdir(git_dir):
        return
    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)
    hook_path = os.path.join(hooks_dir, "pre-commit")
    try:
        with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(PRE_COMMIT_HOOK)
        try:
            os.chmod(hook_path, 0o755)
        except Exception:
            pass
        print(f"{verb} Git pre-commit hook successfully.")
    except Exception as e:
        print(f"Warning: could not write Git pre-commit hook: {e}")


GITATTRIBUTES_LINE = "* text=auto"


def ensure_gitattributes(dest_dir: str, overwrite: bool) -> None:
    """Ensure `.gitattributes` declares `* text=auto` for consistent line endings.

    The old `memory.json binary` masking rule is retired with the knowledge graph.
    Idempotent: appends the line to an existing file only if absent."""
    gitattrib_path = os.path.join(dest_dir, ".gitattributes")
    if os.path.exists(gitattrib_path):
        try:
            with open(gitattrib_path, "r", encoding="utf-8") as f:
                content = f.read()
            if GITATTRIBUTES_LINE not in content:
                sep = "" if content.endswith("\n") or content == "" else "\n"
                with open(gitattrib_path, "a", encoding="utf-8") as f:
                    f.write(f"{sep}{GITATTRIBUTES_LINE}\n")
                print("Appended '* text=auto' to existing .gitattributes")
            else:
                print("Skipping .gitattributes: '* text=auto' already present.")
        except Exception as e:
            print(f"Warning: could not check/append to .gitattributes: {e}")
    else:
        copy_template("gitattributes.template", ".gitattributes", dest_dir, overwrite=overwrite)


GITIGNORE_AETHEL_LINE = ".aethel/"


def ensure_aethel_gitignored(dest_dir: str) -> None:
    """Ensure `.gitignore` ignores the per-session `.aethel/` tree.

    Idempotent (like `ensure_gitattributes`): appends the line to an existing
    `.gitignore` only if absent, creating the file when missing. The whole
    session tree is local scratch — never committed."""
    gitignore_path = os.path.join(dest_dir, ".gitignore")
    try:
        if os.path.exists(gitignore_path):
            with open(gitignore_path, "r", encoding="utf-8") as f:
                content = f.read()
            lines = {ln.strip().rstrip("/") for ln in content.splitlines()}
            if ".aethel" in lines:
                print("Skipping .gitignore: '.aethel/' already present.")
                return
            sep = "" if content.endswith("\n") or content == "" else "\n"
            with open(gitignore_path, "a", encoding="utf-8") as f:
                f.write(f"{sep}\n# Per-session Aethel working dir (local scratch)\n{GITIGNORE_AETHEL_LINE}\n")
            print("Appended '.aethel/' to existing .gitignore")
        else:
            with open(gitignore_path, "w", encoding="utf-8") as f:
                f.write(f"# Per-session Aethel working dir (local scratch)\n{GITIGNORE_AETHEL_LINE}\n")
            print("Created .gitignore with '.aethel/'")
    except Exception as e:
        print(f"Warning: could not check/append to .gitignore: {e}")


RECIPES_DIRNAME = "recipes"
ADDENDUM_NAME = "AETHEL_RECIPE_ADDENDUM.md"


class RecipeError(Exception):
    """A recipe folder is malformed (missing or marker-less addendum)."""


def _is_cache_dir(name: str) -> bool:
    """Directories that are build/lint caches, never recipes or config sources."""
    return name.startswith(".") or name.endswith("_cache") or name == "__pycache__"


def discover_recipes(base_dir: str | None = None) -> dict[str, dict[str, Any]]:
    """Discover recipes by scanning a recipes base directory at runtime.

    A recipe is a sub-directory (cache dirs excluded) containing an
    ``AETHEL_RECIPE_ADDENDUM.md`` whose managed-block BEGIN marker yields the
    sentinel. ``configs`` are the recipe's top-level files minus the addendum.
    Returns ``{name: {"sentinel": "id=<id>", "configs": [...]}}`` — the same shape
    the old hard-coded ``RECIPES`` dict had, so callers are unaffected.

    Raises ``RecipeError`` when a recipe folder lacks a usable addendum (taboos
    #5/#8: a malformed recipe is a packaging error, not a silent skip). An empty
    folder (no addendum, no configs) is warned about and skipped.

    ``base_dir`` is the single seam for tests / future relocation; it defaults to
    the in-package ``templates/recipes`` directory.
    """
    if base_dir is None:
        base_dir = os.path.join(TEMPLATES_DIR, RECIPES_DIRNAME)
    recipes: dict[str, dict[str, Any]] = {}
    if not os.path.isdir(base_dir):
        return recipes

    for name in sorted(os.listdir(base_dir)):
        rdir = os.path.join(base_dir, name)
        if not os.path.isdir(rdir) or _is_cache_dir(name):
            continue

        # Config files keep their leading dot (.ruff.toml, .eslintrc.json); only
        # sub-directories (.ruff_cache, __pycache__) are non-configs, and the
        # os.path.isfile filter already drops them.
        entries = sorted(os.listdir(rdir))
        addendum_present = ADDENDUM_NAME in entries
        configs = [
            e for e in entries
            if e != ADDENDUM_NAME and os.path.isfile(os.path.join(rdir, e))
        ]

        if not addendum_present and not configs:
            print(f"Warning: recipe folder '{name}' is empty; skipping.")
            continue
        if not addendum_present:
            raise RecipeError(f"Recipe '{name}' is missing {ADDENDUM_NAME}.")

        with open(os.path.join(rdir, ADDENDUM_NAME), "r", encoding="utf-8") as f:
            block_id = parse_block_id(f.read())
        if block_id is None:
            raise RecipeError(
                f"Recipe '{name}' addendum has no AETHEL:MANAGED:BEGIN id=... marker."
            )

        recipes[name] = {"sentinel": f"id={block_id}", "configs": configs}
    return recipes


def apply_recipe(recipe: str, dest_dir: str, force: bool) -> None:
    meta = discover_recipes().get(recipe)
    if meta is None:
        print(f"Error: Recipe '{recipe}' templates not found.")
        return
    recipe_src_dir = os.path.join(TEMPLATES_DIR, RECIPES_DIRNAME, recipe)

    print(f"Deploying standard rules and configurations for recipe '{recipe}'...")
    for fname in meta["configs"]:
        src_file = os.path.join(recipe_src_dir, fname)
        dest_file = os.path.join(dest_dir, fname)
        if os.path.exists(dest_file) and not force:
            print(f"Skipping existing linter configuration: {fname}")
        else:
            try:
                shutil.copy2(src_file, dest_file)
                print(f"Created: {fname}")
            except Exception as e:
                print(f"Error copying recipe file {fname}: {e}")

    _ensure_recipe_addendum(recipe, dest_dir)


def _ensure_recipe_addendum(recipe: str, dest_dir: str) -> None:
    """Append the recipe addendum to AETHEL.md unless its managed block is
    already present (idempotent)."""
    addendum_src = os.path.join(TEMPLATES_DIR, RECIPES_DIRNAME, recipe, ADDENDUM_NAME)
    aethel_path = os.path.join(dest_dir, "AETHEL.md")
    meta = discover_recipes().get(recipe)
    if meta is None or not (os.path.exists(addendum_src) and os.path.exists(aethel_path)):
        return
    sentinel = meta["sentinel"]
    try:
        with open(aethel_path, "r", encoding="utf-8") as f:
            aethel_content = f.read()
        if sentinel in aethel_content:
            return  # already applied
        with open(addendum_src, "r", encoding="utf-8") as f:
            addendum_content = f.read()
        with open(aethel_path, "a", encoding="utf-8") as f:
            f.write(addendum_content)
        print(f"Appended recipe-specific guidelines to AETHEL.md ({recipe})")
    except Exception as e:
        print(f"Warning: could not append recipe guidelines: {e}")


def _installed_recipes_from_text(aethel_content: str) -> list[str]:
    """Recipes whose managed-block sentinel is present in the given AETHEL.md text.

    Sentinel presence (not config-file existence) is the source of truth: a user
    may drop a recipe's config file yet keep its rules, and vice versa.
    """
    return [
        name for name, meta in discover_recipes().items()
        if meta["sentinel"] in aethel_content
    ]


def _installed_recipes(dest_dir: str) -> list[str]:
    """Detect which recipes a workspace already uses, by their AETHEL.md sentinel."""
    aethel_path = os.path.join(dest_dir, "AETHEL.md")
    if not os.path.exists(aethel_path):
        return []
    with open(aethel_path, "r", encoding="utf-8") as f:
        return _installed_recipes_from_text(f.read())


def cmd_init(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Initializing Aethel in: {dest_dir}")
    os.makedirs(dest_dir, exist_ok=True)

    # 1. Handle .gitattributes non-destructively
    ensure_gitattributes(dest_dir, overwrite=args.force)

    # 1b. Ignore the per-session `.aethel/` working-dir tree (sessions begin with
    # `aethel start`, not at init).
    ensure_aethel_gitignored(dest_dir)

    # 2. Rename existing non-Aethel GEMINI.md or CLAUDE.md files to LEGACY_* to preserve them
    for fname, signature in [("GEMINI.md", "Aethel"), ("CLAUDE.md", "Aethel")]:
        fpath = os.path.join(dest_dir, fname)
        if os.path.exists(fpath) and not args.force:
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    f_content = f.read()
                if signature not in f_content:
                    legacy_path = os.path.join(dest_dir, f"LEGACY_{fname}")
                    if os.path.exists(legacy_path):
                        os.remove(legacy_path)
                    os.rename(fpath, legacy_path)
                    print(f"Renamed existing legacy {fname} to LEGACY_{fname}")
            except Exception as e:
                print(f"Warning: could not inspect/rename {fname}: {e}")

    # 3. Copy Aethel templates
    copy_template("AETHEL.md.template", "AETHEL.md", dest_dir, overwrite=args.force)
    copy_template("AGENTS.md.template", "AGENTS.md", dest_dir, overwrite=args.force)
    copy_template("GEMINI.md.template", "GEMINI.md", dest_dir, overwrite=args.force)
    copy_template("CLAUDE.md.template", "CLAUDE.md", dest_dir, overwrite=args.force)
    copy_template("CONTEXT.md.template", "CONTEXT.md", dest_dir, overwrite=args.force)
    copy_template("aethel.toml.template", "aethel.toml", dest_dir, overwrite=args.force)
    copy_template("AETHEL_ONBOARDING.md.template", "AETHEL_ONBOARDING.md", dest_dir, overwrite=args.force)

    # 4. Copy .agents plugin and the knowledge/ topic-tree seed
    copy_template_dir(".agents", ".agents", dest_dir, overwrite=args.force)
    copy_template_dir("knowledge", "knowledge", dest_dir, overwrite=args.force)

    # 5. Create wrapper prompt_linter.py
    linter_wrapper_path = os.path.join(dest_dir, "prompt_linter.py")
    if os.path.exists(linter_wrapper_path) and not args.force:
        print("Skipping existing prompt_linter.py wrapper.")
    else:
        write_linter_wrapper(dest_dir)
        print("Created prompt_linter.py wrapper script.")

    # 6. Configure Git pre-commit hook if .git folder is present
    write_pre_commit_hook(dest_dir, "Configured")

    # 7. Copy stack-specific linter recipes if requested
    recipe = getattr(args, "recipe", None)
    if recipe:
        available = discover_recipes()
        if recipe not in available:
            names = ", ".join(sorted(available)) or "(none found)"
            print(f"Error: unknown recipe '{recipe}'. Available recipes: {names}")
            sys.exit(2)
        apply_recipe(recipe, dest_dir, force=args.force)

    print("Aethel initialization complete. Populate the CONTEXT.md index and knowledge/ topic files (see AETHEL_ONBOARDING.md).")


def cmd_lint(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Linting Aethel workspace: {dest_dir}")
    # Forward to consolidated linter cli main by mimicking argv
    sys.argv = [sys.argv[0], "--dir", dest_dir]
    from aethel.linter import main
    main()


def _update_aethel_md(dest_dir: str) -> None:
    """Refresh AETHEL.md's managed core block, preserving user content.

    If the destination has the managed markers, only the core block is replaced
    (custom rules and recipe addenda below it survive untouched). A timestamped
    backup is always written. Legacy files without markers fall back to a full
    template rewrite so they gain the managed structure going forward.
    """
    aethel_path = os.path.join(dest_dir, "AETHEL.md")
    new_template = render_template("AETHEL.md.template", dest_dir)
    if new_template is None:
        return

    if not os.path.exists(aethel_path):
        copy_template("AETHEL.md.template", "AETHEL.md", dest_dir, overwrite=True)
        return

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = f"{aethel_path}.bak.{timestamp}"
    shutil.copy2(aethel_path, backup_path)
    print(f"Created backup of AETHEL.md at {backup_path}")

    with open(aethel_path, "r", encoding="utf-8") as f:
        current = f.read()
    # Capture installed recipes from the ORIGINAL content before any rewrite —
    # a template rewrite would erase the sentinels we detect them by.
    installed_before = _installed_recipes_from_text(current)

    new_core = extract_managed_block(new_template, "aethel-core")
    merged, replaced = (current, False)
    if new_core is not None:
        merged, replaced = replace_managed_block(current, new_core, "aethel-core")

    if replaced:
        with open(aethel_path, "w", encoding="utf-8") as f:
            f.write(merged)
        print("Refreshed AETHEL.md managed core block (custom rules preserved).")
    else:
        # Legacy file without markers: rewrite from template, then re-apply recipes.
        with open(aethel_path, "w", encoding="utf-8") as f:
            f.write(new_template)
        print("AETHEL.md had no managed markers; rewrote from template (backup retained).")
        for recipe in installed_before:
            _ensure_recipe_addendum(recipe, dest_dir)


def cmd_update(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Updating central Aethel structures in: {dest_dir}")

    # 1. Handle .gitattributes (append if exists)
    ensure_gitattributes(dest_dir, overwrite=True)

    # 1b. Ensure the per-session `.aethel/` tree is gitignored (idempotent).
    ensure_aethel_gitignored(dest_dir)

    # 2. Merge .agents plugin (non-destructive: keeps user-added files)
    merge_template_dir(".agents", ".agents", dest_dir)

    # 3. Refresh AETHEL.md managed core, preserving customizations
    _update_aethel_md(dest_dir)

    # 4. Overwrite redirection stubs (AGENTS.md, GEMINI.md, CLAUDE.md) and onboarding gate
    copy_template("AGENTS.md.template", "AGENTS.md", dest_dir, overwrite=True)
    copy_template("GEMINI.md.template", "GEMINI.md", dest_dir, overwrite=True)
    copy_template("CLAUDE.md.template", "CLAUDE.md", dest_dir, overwrite=True)
    copy_template("AETHEL_ONBOARDING.md.template", "AETHEL_ONBOARDING.md", dest_dir, overwrite=True)

    # 5. Re-create linter wrapper
    write_linter_wrapper(dest_dir)
    print("Updated prompt_linter.py wrapper script.")

    # 6. Re-create Git pre-commit hook if .git folder is present
    write_pre_commit_hook(dest_dir, "Updated")

    print("Central structures successfully updated.")


def cmd_start(args: argparse.Namespace) -> None:
    """Open a NEW Route B session, reconciling the previous one on start.

    A validated previous session is archived under `.aethel/archive/<id>/`; an
    interrupted (un-`done`) one under `.aethel/archive/_incomplete/<id>/`."""
    dest_dir = os.path.abspath(args.path)
    cfg = load_config(dest_dir)
    moved = session.reconcile(dest_dir, cfg)
    if moved:
        rel = os.path.relpath(moved, dest_dir)
        print(f"Reconciled previous session -> {rel}")
    session_dir = session.start_session(dest_dir, args.slug, cfg)
    rel_session = os.path.relpath(session_dir, dest_dir)
    print(f"Opened session: {rel_session}")
    print("Author implementation_plan.md / task.md / walkthrough.md inside this directory.")


def cmd_done(args: argparse.Namespace) -> None:
    """Final Route B step: re-validate the active session's report and mark it done.

    Re-runs `check_report_file` against the active session; on success writes
    `status=validated` to the manifest, on failure refuses (exit 1, session stays
    `active`). No active session is an error."""
    dest_dir = os.path.abspath(args.path)
    cfg = load_config(dest_dir)
    session_dir = session.current_session_dir(dest_dir, cfg)
    if session_dir is None:
        print("Error: no active Aethel session. Run `aethel start` to open one.")
        sys.exit(1)

    errors, warnings = check_report_file(dest_dir, cfg)
    for w in warnings:
        print(f"Warning: {w}")
    if errors:
        print("Cannot mark session done — walkthrough.md is missing or malformed:")
        for e in errors:
            print(f"  - {e}")
        print("Author a valid session report, then re-run `aethel done`. Session left active.")
        sys.exit(1)

    session.mark_validated(dest_dir, cfg)
    print(f"Session validated: {os.path.relpath(session_dir, dest_dir)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Aethel: AI Context & Memory CLI Management Utility")
    subparsers = parser.add_subparsers(dest="command", help="Commands to run")

    # init subcommand
    p_init = subparsers.add_parser("init", help="Initialize Aethel in a workspace")
    p_init.add_argument("path", nargs="?", default=".", help="Directory to initialize (default: current)")
    p_init.add_argument("-f", "--force", action="store_true", help="Force overwrite of existing files")
    p_init.add_argument("-r", "--recipe", help="Deploy standard linter recipes/configs for the chosen stack (discovered from templates/recipes)")
    p_init.set_defaults(func=cmd_init)

    # lint subcommand
    p_lint = subparsers.add_parser("lint", help="Validate workspace plan files and knowledge-index integrity")
    p_lint.add_argument("path", nargs="?", default=".", help="Workspace path to lint (default: current)")
    p_lint.set_defaults(func=cmd_lint)

    # update subcommand
    p_update = subparsers.add_parser("update", help="Update Aethel core files & plugins to latest version")
    p_update.add_argument("path", nargs="?", default=".", help="Workspace path to update (default: current)")
    p_update.set_defaults(func=cmd_update)

    # start subcommand: open a new Route B session (reconciles the previous one)
    p_start = subparsers.add_parser("start", help="Open a new Route B session under .aethel/ (reconciles the previous one)")
    p_start.add_argument("slug", nargs="?", default=None, help="Optional slug for the run-id (sanitized to kebab-case)")
    p_start.add_argument("--path", default=".", help="Workspace path (default: current)")
    p_start.set_defaults(func=cmd_start)

    # done subcommand: re-validate the active session report and mark it validated
    p_done = subparsers.add_parser("done", help="Re-validate the active session's walkthrough.md and mark it validated")
    p_done.add_argument("--path", default=".", help="Workspace path (default: current)")
    p_done.set_defaults(func=cmd_done)

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Fetch and call the registered subcommand function
    func = getattr(args, "func", None)
    if func:
        func(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
