import argparse
import os
import shutil
import sys

from aethel.linter import run_linter

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")


# Helper to copy template files
def copy_template(src_name: str, dest_name: str, dest_dir: str, overwrite: bool = False) -> bool:
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    dest_path = os.path.join(dest_dir, dest_name)

    if not os.path.exists(src_path):
        print(f"Error: Template source '{src_path}' not found.")
        return False

    if os.path.exists(dest_path) and not overwrite:
        print(f"Skipping existing file: {dest_name}")
        return False

    abs_workspace_root = os.path.abspath(dest_dir).replace('\\', '/')
    try:
        with open(src_path, "r", encoding="utf-8") as f:
            content = f.read()

        content = content.replace("{WORKSPACE_ROOT}", abs_workspace_root)

        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(content)

        try:
            shutil.copymode(src_path, dest_path)
        except Exception:
            pass

        print(f"Created/Updated: {dest_name}")
        return True
    except Exception as e:
        print(f"Error copying template {src_name}: {e}")
        return False


# Helper to recursively copy directories
def copy_template_dir(src_name: str, dest_name: str, dest_dir: str, overwrite: bool = False) -> bool:
    src_path = os.path.join(TEMPLATES_DIR, src_name)
    dest_path = os.path.join(dest_dir, dest_name)

    if not os.path.exists(src_path):
        print(f"Error: Template folder source '{src_path}' not found.")
        return False

    if os.path.exists(dest_path):
        if overwrite:
            shutil.rmtree(dest_path)
        else:
            print(f"Skipping existing folder: {dest_name}")
            return False

    shutil.copytree(src_path, dest_path)
    print(f"Created/Updated folder: {dest_name}")
    return True


def cmd_init(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Initializing Aethel in: {dest_dir}")
    os.makedirs(dest_dir, exist_ok=True)

    # 1. Handle .gitattributes non-destructively
    gitattrib_path = os.path.join(dest_dir, ".gitattributes")
    if os.path.exists(gitattrib_path):
        try:
            with open(gitattrib_path, "r", encoding="utf-8") as f:
                gitattrib_content = f.read()
            if "memory.json" not in gitattrib_content:
                with open(gitattrib_path, "a", encoding="utf-8") as f:
                    f.write("\nmemory.json merge=binary\n")
                print("Appended memory.json attribute to existing .gitattributes")
            else:
                print("Skipping .gitattributes: memory.json attribute already exists.")
        except Exception as e:
            print(f"Warning: could not check/append to .gitattributes: {e}")
    else:
        copy_template("gitattributes.template", ".gitattributes", dest_dir, overwrite=args.force)

    # 2. Rename existing non-Aethel GEMINI.md or CLAUDE.md files to LEGACY_* to preserve them
    for fname, signature in [("GEMINI.md", "Aethel"), ("CLAUDE.md", "Aethel")]:
        fpath = os.path.join(dest_dir, fname)
        if os.path.exists(fpath) and not args.force:
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    f_content = f.read()
                if signature not in f_content:
                    legacy_path = os.path.join(dest_dir, f"LEGACY_{fname}")
                    if os.path.exists(legacy_path):
                        os.remove(legacy_path)
                    os.rename(fpath, legacy_path)
                    print(f"Renamed existing legacy {fname} to LEGACY_{fname}")
            except Exception as e:
                print(f"Warning: could not inspect/rename {fname}: {e}")

    # 3. Copy Aethel templates
    copy_template("AETHEL.md.template", "AETHEL.md", dest_dir, overwrite=args.force)
    copy_template("GEMINI.md.template", "GEMINI.md", dest_dir, overwrite=args.force)
    copy_template("CLAUDE.md.template", "CLAUDE.md", dest_dir, overwrite=args.force)
    copy_template("CONTEXT.md.template", "CONTEXT.md", dest_dir, overwrite=args.force)
    copy_template("memory.json.template", "memory.json", dest_dir, overwrite=args.force)
    copy_template("AETHEL_ONBOARDING.md.template", "AETHEL_ONBOARDING.md", dest_dir, overwrite=args.force)

    # 4. Copy .agents plugin
    copy_template_dir(".agents", ".agents", dest_dir, overwrite=args.force)

    # 5. Create wrapper prompt_linter.py
    linter_wrapper_path = os.path.join(dest_dir, "prompt_linter.py")
    if os.path.exists(linter_wrapper_path) and not args.force:
        print("Skipping existing prompt_linter.py wrapper.")
    else:
        with open(linter_wrapper_path, "w", encoding="utf-8") as f:
            f.write("""#!/usr/bin/env python3
# Autogenerated Aethel wrapper script
import sys
try:
    from aethel.linter import main
except ImportError:
    print("Error: 'aethel' package not found in Python path. Please run 'pip install aethel' or install it globally.")
    sys.exit(1)

if __name__ == "__main__":
    main()
""")
        print("Created prompt_linter.py wrapper script.")

    # 6. Configure Git pre-commit hook if .git folder is present
    git_dir = os.path.join(dest_dir, ".git")
    if os.path.isdir(git_dir):
        hooks_dir = os.path.join(git_dir, "hooks")
        os.makedirs(hooks_dir, exist_ok=True)
        hook_path = os.path.join(hooks_dir, "pre-commit")
        try:
            with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
                f.write("""#!/bin/sh
# Autogenerated Aethel Git pre-commit hook
echo "=== Running Aethel pre-commit verification ==="
if [ -f "./venv/Scripts/python" ]; then
  ./venv/Scripts/python prompt_linter.py
elif [ -f "./venv/bin/python" ]; then
  ./venv/bin/python prompt_linter.py
else
  python prompt_linter.py
fi
""")
            try:
                os.chmod(hook_path, 0o755)
            except Exception:
                pass
            print("Configured Git pre-commit hook successfully.")
        except Exception as e:
            print(f"Warning: could not write Git pre-commit hook: {e}")

    print("Aethel initialization complete. Please configure your Memory MCP server path in AETHEL_ONBOARDING.md.")


def cmd_lint(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Linting Aethel workspace: {dest_dir}")
    # Forward to consolidated linter cli main by mimicking argv
    sys.argv = [sys.argv[0], "--dir", dest_dir]
    from aethel.linter import main
    main()


def cmd_update(args: argparse.Namespace) -> None:
    dest_dir = os.path.abspath(args.path)
    print(f"Updating central Aethel structures in: {dest_dir}")

    # 1. Handle .gitattributes (append if exists)
    gitattrib_path = os.path.join(dest_dir, ".gitattributes")
    if os.path.exists(gitattrib_path):
        try:
            with open(gitattrib_path, "r", encoding="utf-8") as f:
                gitattrib_content = f.read()
            if "memory.json" not in gitattrib_content:
                with open(gitattrib_path, "a", encoding="utf-8") as f:
                    f.write("\nmemory.json merge=binary\n")
                print("Appended memory.json attribute to existing .gitattributes")
        except Exception as e:
            print(f"Warning: could not check/append to .gitattributes: {e}")
    else:
        copy_template("gitattributes.template", ".gitattributes", dest_dir, overwrite=True)

    # 2. Overwrite .agents plugin directory
    copy_template_dir(".agents", ".agents", dest_dir, overwrite=True)

    # 3. Backup and update central rules (AETHEL.md)
    aethel_path = os.path.join(dest_dir, "AETHEL.md")
    if os.path.exists(aethel_path):
        backup_path = aethel_path + ".bak"
        if os.path.exists(backup_path):
            os.remove(backup_path)
        shutil.copy2(aethel_path, backup_path)
        print(f"Created backup of AETHEL.md at {backup_path}")
    copy_template("AETHEL.md.template", "AETHEL.md", dest_dir, overwrite=True)

    # 4. Overwrite redirection files (GEMINI.md, CLAUDE.md)
    copy_template("GEMINI.md.template", "GEMINI.md", dest_dir, overwrite=True)
    copy_template("CLAUDE.md.template", "CLAUDE.md", dest_dir, overwrite=True)

    # 5. Re-create linter wrapper
    linter_wrapper_path = os.path.join(dest_dir, "prompt_linter.py")
    with open(linter_wrapper_path, "w", encoding="utf-8") as f:
        f.write("""#!/usr/bin/env python3
# Autogenerated Aethel wrapper script
import sys
try:
    from aethel.linter import main
except ImportError:
    print("Error: 'aethel' package not found in Python path. Please run 'pip install aethel' or install it globally.")
    sys.exit(1)

if __name__ == "__main__":
    main()
""")
    print("Updated prompt_linter.py wrapper script.")

    # 6. Re-create Git pre-commit hook if .git folder is present
    git_dir = os.path.join(dest_dir, ".git")
    if os.path.isdir(git_dir):
        hooks_dir = os.path.join(git_dir, "hooks")
        os.makedirs(hooks_dir, exist_ok=True)
        hook_path = os.path.join(hooks_dir, "pre-commit")
        try:
            with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
                f.write("""#!/bin/sh
# Autogenerated Aethel Git pre-commit hook
echo "=== Running Aethel pre-commit verification ==="
if [ -f "./venv/Scripts/python" ]; then
  ./venv/Scripts/python prompt_linter.py
elif [ -f "./venv/bin/python" ]; then
  ./venv/bin/python prompt_linter.py
else
  python prompt_linter.py
fi
""")
            try:
                os.chmod(hook_path, 0o755)
            except Exception:
                pass
            print("Updated Git pre-commit hook successfully.")
        except Exception as e:
            print(f"Warning: could not write Git pre-commit hook: {e}")

    print("Central structures successfully updated.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Aethel: AI Context & Memory CLI Management Utility")
    subparsers = parser.add_subparsers(dest="command", help="Commands to run")

    # init subcommand
    p_init = subparsers.add_parser("init", help="Initialize Aethel in a workspace")
    p_init.add_argument("path", nargs="?", default=".", help="Directory to initialize (default: current)")
    p_init.add_argument("-f", "--force", action="store_true", help="Force overwrite of existing files")
    p_init.set_defaults(func=cmd_init)

    # lint subcommand
    p_lint = subparsers.add_parser("lint", help="Validate workspace plan files and memory.json integrity")
    p_lint.add_argument("path", nargs="?", default=".", help="Workspace path to lint (default: current)")
    p_lint.set_defaults(func=cmd_lint)

    # update subcommand
    p_update = subparsers.add_parser("update", help="Update Aethel core files & plugins to latest version")
    p_update.add_argument("path", nargs="?", default=".", help="Workspace path to update (default: current)")
    p_update.set_defaults(func=cmd_update)

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Fetch and call the registered subcommand function
    func = getattr(args, "func", None)
    if func:
        func(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
